categories:
  music:
    dir: /mnt/nfs/pt/ytb_music
    enabled: true
    max_size_gb: 0
    name: Music
cleanup_policy: oldest_first
default_format: video
default_quality: 1080p
disk_limit_enabled: false
host: 0.0.0.0
log_dir: logs
max_music_size_gb: 0
max_video_size_gb: 0
music_dir: /mnt/nfs/pt/music_video
port: 1917
retention_days: 0
strip_playlist: true
video_dir: /mnt/nfs/pt/ytb_video
