services:
  ytbdl:
    build: .
    container_name: ytbdl
    restart: unless-stopped
    ports:
      - "1917:1917"
    volumes:
      - ./video:/app/video
      - ./music:/app/music
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Asia/Shanghai
